CREATE PUBLIC DATABASE LINK DB_LINK_AEROLINEA
CONNECT TO C##AEROLINEA IDENTIFIED BY oracle
USING '(DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.0.10)(PORT = 1522))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = free)
    )
  )
';

SELECT * FROM TBL_BOLETOS@DB_LINK_AEROLINEA;
SELECT * FROM TBL_AVIONES@DB_LINK_AEROLINEA;


----EN CASO DE SER NECESARIO (EN SYSTEM):
DROP PUBLIC DATABASE LINK DB_LINK_AEROLINEA;