CREATE PUBLIC DATABASE LINK DBLINK_AEROLINEA1
CONNECT TO C##AEROLINEA IDENTIFIED BY oracle4
USING '(DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.1.19)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = XE)
    )
  )
';

SELECT * FROM TBL_BOLETOS@DBLINK_AEROLINEA1;
SELECT * FROM TBL_AVIONES@DBLINK_AEROLINEA1;