-- USER SQL
CREATE USER "C##AEROLINEA" IDENTIFIED BY "oracle"  ;

-- QUOTAS
ALTER USER "C##AEROLINEA" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "C##AEROLINEA" ;
GRANT "RESOURCE" TO "C##AEROLINEA" ;

-- SYSTEM PRIVILEGES
GRANT CREATE VIEW TO "C##AEROLINEA" ;
GRANT CREATE TABLE TO "C##AEROLINEA" ;
GRANT CREATE TYPE TO "C##AEROLINEA" ;
GRANT CREATE SEQUENCE TO "C##AEROLINEA" ;
