
--Funcion para ver si una fecha entre otras dos
CREATE OR REPLACE FUNCTION F_FECHA_ENTRE_DOS_FECHAS (P_FECHA_EVALUAR DATE, P_FECHA_INICIO DATE, P_FECHA_FINAL DATE) 
RETURN VARCHAR2 AS
BEGIN
    IF(P_FECHA_EVALUAR BETWEEN P_FECHA_INICIO AND P_FECHA_FINAL) THEN
        RETURN 'TRUE';
    ELSE
        RETURN 'FALSE';
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR=> '|| SQLERRM);
END;