--- EXTRACCIONES DE LA BASE DE DATOS HOTELES 

--------------------- ENCABEZADO DEL PAQUETE 
CREATE OR REPLACE PACKAGE PKG_ETLS_HOTELES IS
END PKG_ETLS_HOTELES;

--------------------- CUERPO DEL PAQUETE
CREATE OR REPLACE PACKAGE BODY PKG_ETLS_HOTELES IS
END PKG_ETLS_HOTELES;