------------------------ EXTRACCIONES
BEGIN
    PKG_ETLS_AEROLINEA.P_ETL_VUELOS;
    PKG_ETLS_AEROLINEA.P_ETL_ASIENTOS;
    PKG_ETLS_AEROLINEA.P_ETL_ESCALAS;
    PKG_ETLS_AEROLINEA.P_ETL_CLIENTES;
    PKG_ETLS_AEROLINEA.P_ETL_BOLETOS;
    PKG_ETLS_AEROLINEA.P_ETL_FACTURAS;
    PKG_ETLS_AEROLINEA.P_ETL_BOLETO_POR_FACTURA;
    PKG_ETLS_AEROLINEA.P_ETL_SERVICIOS;
    PKG_ETLS_AEROLINEA.P_ETL_SERVICIOS_POR_BOLETO;
    PKG_ETLS_AEROLINEA.P_ETL_EQUIPAJES;
    PKG_ETLS_AEROLINEA.P_ETL_EQUIPAJES_POR_BOLETO;
END;

------------------------ CANTIDAD DE REGISTROS 
